version: "3"
services:
    euphoria:
        build:
            context: .
        image: phoenix:latest
        ports: 
            - "22:22"
            - "23:23"
            - "80:80"
            - "443:443"
        volumes:
            - .:/euphoria